# Generated by Django 5.2.10 on 2026-03-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0002_profile_is_founder_yearlysummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
